try Â¨

let x = 0
throw(este es un error)
catch